<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite064b2f8eb879ee89381b1343a1805be
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DLXPlugins\\PhotoBlock\\' => 22,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DLXPlugins\\PhotoBlock\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite064b2f8eb879ee89381b1343a1805be::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite064b2f8eb879ee89381b1343a1805be::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite064b2f8eb879ee89381b1343a1805be::$classMap;

        }, null, ClassLoader::class);
    }
}
